In [1]:
import numpy as np 
import matplotlib.pyplot as plt

import tensorflow as tf


INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
x = tf.Variable(4.0)
with tf.GradientTape() as tape:
    y = x**2

In [3]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [4]:
dy_dx = tape.gradient(y,x)
dy_dx


<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [5]:
w = tf.Variable(tf.random.normal((4,2)))
w

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.9212279 , -0.1886576 ],
       [ 1.0272133 , -0.2201603 ],
       [-1.0472453 ,  0.24369799],
       [-1.6585059 ,  0.7330584 ]], dtype=float32)>

In [6]:
b = tf.Variable(tf.ones(2,dtype=tf.float32))
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [7]:
x = tf.Variable([[10.,20.,30.,40.]], dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32, numpy=array([[10., 20., 30., 40.]], dtype=float32)>

In [8]:
with tf.GradientTape(persistent=True) as tape:
    y = tf.matmul(x,w) + b
    loss = tf.reduce_mean(y**2)

In [10]:
[dl_dw,dl_db] = tape.gradient(loss,[w,b])

In [11]:
dl_dw

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ -670.0105 ,   313.43494],
       [-1340.021  ,   626.8699 ],
       [-2010.0316 ,   940.3048 ],
       [-2680.042  ,  1253.7397 ]], dtype=float32)>

In [13]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([[10.,20.,30.]])


In [18]:
with tf.GradientTape() as tape:
    y = layer(x)
    loss = tf.reduce_sum(y**2)
grad = tape.gradient(loss,layer.trainable_variables)

In [19]:
grad

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.     , 25.16037],
        [ 0.     , 50.32074],
        [ 0.     , 75.48111]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.      , 2.516037], dtype=float32)>]

In [20]:
y

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.       , 1.2580185]], dtype=float32)>

In [21]:
x1 = tf.Variable(5.0)
x1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [22]:
x2 = tf.Variable(5.0,trainable=False)
x2

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [24]:
x3 = tf.add(x1,x2)
x3

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [25]:
x4 = tf.constant(5.0)
x4

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [26]:
with tf.GradientTape() as tape:
    y = (x1**2) + (x2**2) + (x3**2) + (x4**2) 
grad = tape.gradient(y,[x1,x2,x3,x4])

grad


[<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None, None, None]

In [34]:

x1 = tf.constant(5.)
x2 = tf.Variable(3.0)

with tf.GradientTape() as tape:
    tape.watch(x1)

    y = (x1 ** 2 ) + (x2 ** 2)

y

<tf.Tensor: shape=(), dtype=float32, numpy=34.0>

In [35]:
[dy_dx1, dy_dx2] = tape.gradient(y,[x1,x2])

dy_dx1, dy_dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)