In [1]:
import tensorflow as tf
import numpy as np 

tf.debugging.set_log_device_placement(True)

In [2]:
tf.executing_eagerly()

True

In [3]:
# Scalars
x0 = tf.constant(3)
x0


Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


2021-10-02 06:15:21.963441: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-02 06:15:21.969663: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-02 06:15:21.969929: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-02 06:15:21.970957: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
x0.shape

TensorShape([])

In [5]:
x0.dtype

tf.int32

In [6]:
x0.numpy()

3

In [7]:
result = x0 + 5
result

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [8]:
result.numpy()

8

In [9]:
# Vectors or one dimentional array 

x1 = tf.constant([1.1,2.2,3.3,4.4])

x1


Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [10]:
result1 = x1 + 5
result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [11]:
result1 = x1 + tf.constant(5.0)
result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [12]:
#two dimention array
x2 = tf.constant([[1,2,3,4],
[5,6,7,8]])
x2


Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [13]:
#cast 

x2 = tf.cast(x2,tf.float32)
x2

Executing op Cast in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [14]:
print(x1)
print(x2)

tf.Tensor([1.1 2.2 3.3 4.4], shape=(4,), dtype=float32)
tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32)


In [15]:
#shape have to be compatible to make operation work

result3 = tf.multiply(x1,x2)
result3

Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [16]:
#convert to numpy

arr_x1 = x1.numpy()
arr_x1

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [17]:
#convert array to tensor
arr_x4 = np.array([[10,20],[30,40],[50,60]])
x4 = tf.convert_to_tensor(arr_x4)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


In [18]:
x4

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

In [19]:
#numpy operation on tensor (not recomended , will break computation graph)

np.square(x2)

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]], dtype=float32)

In [20]:
#helpers
#make a shape
t0 = tf.zeros([3,5],tf.int32)
t0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [21]:
t1 = tf.ones([3,5],tf.int32)
t1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [22]:
#reshape (must stay withing the limit of the original shape)

t0_reshaped = tf.reshape(t0,(5,3))
t0_reshaped

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [23]:
v1 = tf.Variable([1.5,2,5],[2,6,8])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1.5, 2. , 5. ], dtype=float32)>

In [24]:
v2 = tf.Variable([1,2,3],[4,5,6])
v2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [25]:
v2 = tf.Variable([[1,2,3],[4,5,6]], dtype=tf.float32)
v2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [26]:
# tensor no mutable variables are

tf.add(v1,v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.5,  4. ,  8. ],
       [ 5.5,  7. , 11. ]], dtype=float32)>

In [27]:
tf.convert_to_tensor(v1)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 2. , 5. ], dtype=float32)>

In [28]:
v1.assign([10,20,30],[40,50,60])

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>