In [1]:
import time
import warnings
import logging
import tensorflow as tf

In [2]:
@tf.function
def add(a,b):
    return a+b
@tf.function
def sub(a,b):
    return a-b
@tf.function
def mul(a,b):
    return a * b
@tf.function
def div(a,b):
    return a / b


In [3]:
print(add(tf.constant(4),tf.constant(4)))

tf.Tensor(8, shape=(), dtype=int32)


2021-10-02 06:13:28.277867: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-02 06:13:28.282555: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-02 06:13:28.282843: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-02 06:13:28.283793: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

In [4]:
print(mul(2,4))

tf.Tensor(8, shape=(), dtype=int32)


In [5]:
print(mul(234,34))

tf.Tensor(7956, shape=(), dtype=int32)


In [6]:
print(mul(13,234923))

tf.Tensor(3053999, shape=(), dtype=int32)


In [7]:
@tf.function
def matmul(a,b):
    return tf.matmul(a,b)
@tf.function
def linear(m,x,c):
    return add(matmul(m,x),c)
    

In [8]:
m = tf.constant([[4.0,5.0,6.0]],tf.float32)
m

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 5., 6.]], dtype=float32)>

In [9]:
x = tf.Variable([[100.0],[100.0],[100.0]], tf.float32)
x

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[100.],
       [100.],
       [100.]], dtype=float32)>

In [10]:
c = tf.constant([[1.0]], tf.float32)
c

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [11]:
  linear(m,x,c)

2021-10-02 06:13:29.623470: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-10-02 06:13:29.623505: W tensorflow/stream_executor/stream.cc:1298] attempting to perform BLAS operation using StreamExecutor without BLAS support


InternalError:  Blas xGEMV launch failed : a.shape=[1,1,3], b.shape=[1,3,1], m=1, n=1, k=3
	 [[{{node StatefulPartitionedCall/MatMul}}]] [Op:__inference_linear_57]

Function call stack:
linear


In [12]:
@tf.function
def pos_neg_check(x):
    reduce_sum = tf.reduce_sum(x)

    if reduce_sum > 0 :
        return tf.constant(1)
    elif reduce_sum == 0 :
        return tf.constant(0)
    else:
        return tf.constant(-1)

In [13]:
pos_neg_check(tf.constant([100,100]))

In [ ]:
num = tf.Variable(7)


Error: Session cannot generate requests

In [ ]:
@tf.function
def add_times(x):
    for i in (tf.range(x)):
        num.assign_add(x)

Error: Session cannot generate requests

In [ ]:
add_times(5)

Error: Session cannot generate requests

In [ ]:
num

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>

In [ ]:
a = tf.Variable(1.0)
b = tf.Variable(2.0)


@tf.function
def f(x,y):
    a.assign(y*b)
    b.assign_add(x*a)
    return a+b

In [ ]:
f(1,2)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>